# Course related settings
COURSE_PHOTO_THUMB_SIZE = (80, 80)
COURSE_PHOTO_THUMB_QUALITY = 85
COURSE_PHOTO_THUMB_FORMAT = "JPEG"
COURSE_RATING_WEIGHT = 10
COURSE_RATING_RANGE = 5
AVERAGE_COURSE_RATING = 3